package com.cross.b2c_provisioning;

import com.cross.ResourceRef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreateGPONServiceResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("crossId")
	private java.lang.String crossId;
	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;

	private java.lang.Integer capacityFree;

	private java.lang.Integer capacityFull;

	private java.lang.String capacityUnitSymbol;

	private Integer channelNumber;

	private java.util.List<com.cross.CustomAttribute> customAttributes;

	private java.lang.String description;

	private ResourceRef endNode;

	private java.util.List<com.cross.ExternalId> externalIds;

	private java.lang.String routingPolicy;

	private java.lang.Integer mainFibrilCount;

	private java.lang.Integer protectionFibrilCount;

	private com.cross.ResourceRef linkType;

	private com.cross.ResourceRef status;

	private com.cross.ResourceRef material;

	private java.lang.String geometry;

	private com.cross.ResourceRef startNode;

	private com.cross.ResourceRef nonChannelProvider;

	private java.util.List<com.cross.Category> categories;

	private java.util.List<com.cross.Provider> providers;

	public CreateGPONServiceResponse() {
	}

	public java.lang.String getCrossId() {
		return this.crossId;
	}

	public void setCrossId(java.lang.String crossId) {
		this.crossId = crossId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getCapacityFree() {
		return this.capacityFree;
	}

	public void setCapacityFree(java.lang.Integer capacityFree) {
		this.capacityFree = capacityFree;
	}

	public java.lang.Integer getCapacityFull() {
		return this.capacityFull;
	}

	public void setCapacityFull(java.lang.Integer capacityFull) {
		this.capacityFull = capacityFull;
	}

	public java.lang.String getCapacityUnitSymbol() {
		return this.capacityUnitSymbol;
	}

	public void setCapacityUnitSymbol(java.lang.String capacityUnitSymbol) {
		this.capacityUnitSymbol = capacityUnitSymbol;
	}

	public java.util.List<com.cross.CustomAttribute> getCustomAttributes() {
		return this.customAttributes;
	}

	public void setCustomAttributes(
			java.util.List<com.cross.CustomAttribute> customAttributes) {
		this.customAttributes = customAttributes;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public com.cross.ResourceRef getEndNode() {
		return this.endNode;
	}

	public void setEndNode(com.cross.ResourceRef endNode) {
		this.endNode = endNode;
	}

	public java.util.List<com.cross.ExternalId> getExternalIds() {
		return this.externalIds;
	}

	public void setExternalIds(java.util.List<com.cross.ExternalId> externalIds) {
		this.externalIds = externalIds;
	}

	public java.lang.String getRoutingPolicy() {
		return this.routingPolicy;
	}

	public void setRoutingPolicy(java.lang.String routingPolicy) {
		this.routingPolicy = routingPolicy;
	}

	public java.lang.Integer getChannelNumber() {
		return this.channelNumber;
	}

	public void setChannelNumber(java.lang.Integer channelNumber) {
		this.channelNumber = channelNumber;
	}

	public java.lang.Integer getMainFibrilCount() {
		return this.mainFibrilCount;
	}

	public void setMainFibrilCount(java.lang.Integer mainFibrilCount) {
		this.mainFibrilCount = mainFibrilCount;
	}

	public java.lang.Integer getProtectionFibrilCount() {
		return this.protectionFibrilCount;
	}

	public void setProtectionFibrilCount(java.lang.Integer protectionFibrilCount) {
		this.protectionFibrilCount = protectionFibrilCount;
	}

	public com.cross.ResourceRef getLinkType() {
		return this.linkType;
	}

	public void setLinkType(com.cross.ResourceRef linkType) {
		this.linkType = linkType;
	}

	public com.cross.ResourceRef getStatus() {
		return this.status;
	}

	public void setStatus(com.cross.ResourceRef status) {
		this.status = status;
	}

	public com.cross.ResourceRef getMaterial() {
		return this.material;
	}

	public void setMaterial(com.cross.ResourceRef material) {
		this.material = material;
	}

	public java.lang.String getGeometry() {
		return this.geometry;
	}

	public void setGeometry(java.lang.String geometry) {
		this.geometry = geometry;
	}

	public com.cross.ResourceRef getStartNode() {
		return this.startNode;
	}

	public void setStartNode(com.cross.ResourceRef startNode) {
		this.startNode = startNode;
	}

	public com.cross.ResourceRef getNonChannelProvider() {
		return this.nonChannelProvider;
	}

	public void setNonChannelProvider(com.cross.ResourceRef nonChannelProvider) {
		this.nonChannelProvider = nonChannelProvider;
	}

	public java.util.List<com.cross.Category> getCategories() {
		return this.categories;
	}

	public void setCategories(java.util.List<com.cross.Category> categories) {
		this.categories = categories;
	}

	public java.util.List<com.cross.Provider> getProviders() {
		return this.providers;
	}

	public void setProviders(java.util.List<com.cross.Provider> providers) {
		this.providers = providers;
	}

	public CreateGPONServiceResponse(java.lang.String crossId,
			java.lang.String name, java.lang.Integer capacityFree,
			java.lang.Integer capacityFull,
			java.lang.String capacityUnitSymbol,
			java.lang.Integer channelNumber,
			java.util.List<com.cross.CustomAttribute> customAttributes,
			java.lang.String description, com.cross.ResourceRef endNode,
			java.util.List<com.cross.ExternalId> externalIds,
			java.lang.String routingPolicy, java.lang.Integer mainFibrilCount,
			java.lang.Integer protectionFibrilCount,
			com.cross.ResourceRef linkType, com.cross.ResourceRef status,
			com.cross.ResourceRef material, java.lang.String geometry,
			com.cross.ResourceRef startNode,
			com.cross.ResourceRef nonChannelProvider,
			java.util.List<com.cross.Category> categories,
			java.util.List<com.cross.Provider> providers) {
		this.crossId = crossId;
		this.name = name;
		this.capacityFree = capacityFree;
		this.capacityFull = capacityFull;
		this.capacityUnitSymbol = capacityUnitSymbol;
		this.channelNumber = channelNumber;
		this.customAttributes = customAttributes;
		this.description = description;
		this.endNode = endNode;
		this.externalIds = externalIds;
		this.routingPolicy = routingPolicy;
		this.mainFibrilCount = mainFibrilCount;
		this.protectionFibrilCount = protectionFibrilCount;
		this.linkType = linkType;
		this.status = status;
		this.material = material;
		this.geometry = geometry;
		this.startNode = startNode;
		this.nonChannelProvider = nonChannelProvider;
		this.categories = categories;
		this.providers = providers;
	}

}