package com.cross.b2c_provisioning;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GPONServiceLink implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("crossId")
	private java.lang.String crossId;
	@org.kie.api.definition.type.Label("reversed")
	private java.lang.Boolean reversed;

	public GPONServiceLink() {
	}

	public java.lang.String getCrossId() {
		return this.crossId;
	}

	public void setCrossId(java.lang.String crossId) {
		this.crossId = crossId;
	}

	public java.lang.Boolean getReversed() {
		return this.reversed;
	}

	public void setReversed(java.lang.Boolean reversed) {
		this.reversed = reversed;
	}

	public GPONServiceLink(java.lang.String crossId, java.lang.Boolean reversed) {
		this.crossId = crossId;
		this.reversed = reversed;
	}

}