package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Category implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String treeName;

	public Category() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getTreeName() {
		return this.treeName;
	}

	public void setTreeName(java.lang.String treeName) {
		this.treeName = treeName;
	}

	public Category(java.lang.String name, java.lang.String treeName) {
		this.name = name;
		this.treeName = treeName;
	}

}