package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CpeComponentBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.cross.Resource> resources;

	public CpeComponentBody() {
	}

	public java.util.List<com.cross.Resource> getResources() {
		return this.resources;
	}

	public void setResources(java.util.List<com.cross.Resource> resources) {
		this.resources = resources;
	}

	public CpeComponentBody(java.util.List<com.cross.Resource> resources) {
		this.resources = resources;
	}

}