package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreateProjectRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String creator;
	private java.lang.String name;
	private java.lang.String projectTypeDiscriminator;

	public CreateProjectRequest() {
	}

	public java.lang.String getCreator() {
		return this.creator;
	}

	public void setCreator(java.lang.String creator) {
		this.creator = creator;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getProjectTypeDiscriminator() {
		return this.projectTypeDiscriminator;
	}

	public void setProjectTypeDiscriminator(
			java.lang.String projectTypeDiscriminator) {
		this.projectTypeDiscriminator = projectTypeDiscriminator;
	}

	public CreateProjectRequest(java.lang.String creator,
			java.lang.String name, java.lang.String projectTypeDiscriminator) {
		this.creator = creator;
		this.name = name;
		this.projectTypeDiscriminator = projectTypeDiscriminator;
	}

}