package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreateProjectResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String crossId;
	private java.lang.String name;

	public CreateProjectResponse() {
	}

	public java.lang.String getCrossId() {
		return this.crossId;
	}

	public void setCrossId(java.lang.String crossId) {
		this.crossId = crossId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public CreateProjectResponse(java.lang.String crossId, java.lang.String name) {
		this.crossId = crossId;
		this.name = name;
	}

}