package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomAttributeValue implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String value;
	private java.lang.String name;
	private java.lang.Boolean _meta_valuesImplicitRemove;

	public CustomAttributeValue() {
	}

	public java.lang.String getValue() {
		return this.value;
	}

	public void setValue(java.lang.String value) {
		this.value = value;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Boolean get_meta_valuesImplicitRemove() {
		return this._meta_valuesImplicitRemove;
	}

	public void set_meta_valuesImplicitRemove(
			java.lang.Boolean _meta_valuesImplicitRemove) {
		this._meta_valuesImplicitRemove = _meta_valuesImplicitRemove;
	}

	public CustomAttributeValue(java.lang.String value, java.lang.String name,
			java.lang.Boolean _meta_valuesImplicitRemove) {
		this.value = value;
		this.name = name;
		this._meta_valuesImplicitRemove = _meta_valuesImplicitRemove;
	}

}