package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomAttribute implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.util.List<java.lang.String> values;

	private java.lang.String value;

	private java.lang.Boolean _meta_valuesImplicitRemove;

	public CustomAttribute() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.util.List<java.lang.String> getValues() {
		return this.values;
	}

	public void setValues(java.util.List<java.lang.String> values) {
		this.values = values;
	}

	public java.lang.String getValue() {
		return this.value;
	}

	public void setValue(java.lang.String value) {
		this.value = value;
	}

	public java.lang.Boolean get_meta_valuesImplicitRemove() {
		return this._meta_valuesImplicitRemove;
	}

	public void set_meta_valuesImplicitRemove(
			java.lang.Boolean _meta_valuesImplicitRemove) {
		this._meta_valuesImplicitRemove = _meta_valuesImplicitRemove;
	}

	public CustomAttribute(java.lang.String name,
			java.util.List<java.lang.String> values, java.lang.String value,
			java.lang.Boolean _meta_valuesImplicitRemove) {
		this.name = name;
		this.values = values;
		this.value = value;
		this._meta_valuesImplicitRemove = _meta_valuesImplicitRemove;
	}

}