package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DecisionList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("decisions")
	private java.util.List<java.lang.String> decisions;

	public DecisionList() {
	}

	public java.util.List<java.lang.String> getDecisions() {
		return this.decisions;
	}

	public void setDecisions(java.util.List<java.lang.String> decisions) {
		this.decisions = decisions;
	}

	public DecisionList(java.util.List<java.lang.String> decisions) {
		this.decisions = decisions;
	}

}