package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IPAddressCPEBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean _meta_parentsImplicitRemove;
	private java.lang.Boolean _meta_categoriesImplicitRemove;
	private java.lang.Boolean _meta_aliasesImplicitRemove;
	private java.lang.Boolean _meta_externalIdsImplicitRemove;
	private java.lang.Boolean _meta_nodeTypesImplicitRemove;

	private java.util.List<com.cross.CustomAttributeValue> customAttributes;

	public IPAddressCPEBody() {
	}

	public java.lang.Boolean get_meta_parentsImplicitRemove() {
		return this._meta_parentsImplicitRemove;
	}

	public void set_meta_parentsImplicitRemove(
			java.lang.Boolean _meta_parentsImplicitRemove) {
		this._meta_parentsImplicitRemove = _meta_parentsImplicitRemove;
	}

	public java.lang.Boolean get_meta_categoriesImplicitRemove() {
		return this._meta_categoriesImplicitRemove;
	}

	public void set_meta_categoriesImplicitRemove(
			java.lang.Boolean _meta_categoriesImplicitRemove) {
		this._meta_categoriesImplicitRemove = _meta_categoriesImplicitRemove;
	}

	public java.lang.Boolean get_meta_aliasesImplicitRemove() {
		return this._meta_aliasesImplicitRemove;
	}

	public void set_meta_aliasesImplicitRemove(
			java.lang.Boolean _meta_aliasesImplicitRemove) {
		this._meta_aliasesImplicitRemove = _meta_aliasesImplicitRemove;
	}

	public java.lang.Boolean get_meta_externalIdsImplicitRemove() {
		return this._meta_externalIdsImplicitRemove;
	}

	public void set_meta_externalIdsImplicitRemove(
			java.lang.Boolean _meta_externalIdsImplicitRemove) {
		this._meta_externalIdsImplicitRemove = _meta_externalIdsImplicitRemove;
	}

	public java.lang.Boolean get_meta_nodeTypesImplicitRemove() {
		return this._meta_nodeTypesImplicitRemove;
	}

	public void set_meta_nodeTypesImplicitRemove(
			java.lang.Boolean _meta_nodeTypesImplicitRemove) {
		this._meta_nodeTypesImplicitRemove = _meta_nodeTypesImplicitRemove;
	}

	public java.util.List<com.cross.CustomAttributeValue> getCustomAttributes() {
		return this.customAttributes;
	}

	public void setCustomAttributes(
			java.util.List<com.cross.CustomAttributeValue> customAttributes) {
		this.customAttributes = customAttributes;
	}

	public IPAddressCPEBody(java.lang.Boolean _meta_parentsImplicitRemove,
			java.lang.Boolean _meta_categoriesImplicitRemove,
			java.lang.Boolean _meta_aliasesImplicitRemove,
			java.lang.Boolean _meta_externalIdsImplicitRemove,
			java.lang.Boolean _meta_nodeTypesImplicitRemove,
			java.util.List<com.cross.CustomAttributeValue> customAttributes) {
		this._meta_parentsImplicitRemove = _meta_parentsImplicitRemove;
		this._meta_categoriesImplicitRemove = _meta_categoriesImplicitRemove;
		this._meta_aliasesImplicitRemove = _meta_aliasesImplicitRemove;
		this._meta_externalIdsImplicitRemove = _meta_externalIdsImplicitRemove;
		this._meta_nodeTypesImplicitRemove = _meta_nodeTypesImplicitRemove;
		this.customAttributes = customAttributes;
	}

}