package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Provider implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String consumptionType;
	private java.lang.Boolean reversed;
	private java.lang.Integer orderNumber;
	private java.lang.Integer fibrilNumber;
	private com.cross.ResourceRef providerRef;

	public Provider() {
	}

	public java.lang.String getConsumptionType() {
		return this.consumptionType;
	}

	public void setConsumptionType(java.lang.String consumptionType) {
		this.consumptionType = consumptionType;
	}

	public java.lang.Boolean getReversed() {
		return this.reversed;
	}

	public void setReversed(java.lang.Boolean reversed) {
		this.reversed = reversed;
	}

	public java.lang.Integer getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(java.lang.Integer orderNumber) {
		this.orderNumber = orderNumber;
	}

	public java.lang.Integer getFibrilNumber() {
		return this.fibrilNumber;
	}

	public void setFibrilNumber(java.lang.Integer fibrilNumber) {
		this.fibrilNumber = fibrilNumber;
	}

	public com.cross.ResourceRef getProviderRef() {
		return this.providerRef;
	}

	public void setProviderRef(com.cross.ResourceRef providerRef) {
		this.providerRef = providerRef;
	}

	public Provider(java.lang.String consumptionType,
			java.lang.Boolean reversed, java.lang.Integer orderNumber,
			java.lang.Integer fibrilNumber, com.cross.ResourceRef providerRef) {
		this.consumptionType = consumptionType;
		this.reversed = reversed;
		this.orderNumber = orderNumber;
		this.fibrilNumber = fibrilNumber;
		this.providerRef = providerRef;
	}

}