package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Resource implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String crossId;
	private java.lang.Boolean primary;

	private ResourceRef resourceRef;

	public Resource() {
	}

	public java.lang.String getCrossId() {
		return this.crossId;
	}

	public void setCrossId(java.lang.String crossId) {
		this.crossId = crossId;
	}

	public java.lang.Boolean getPrimary() {
		return this.primary;
	}

	public void setPrimary(java.lang.Boolean primary) {
		this.primary = primary;
	}

	public com.cross.ResourceRef getResourceRef() {
		return this.resourceRef;
	}

	public void setResourceRef(com.cross.ResourceRef resourceRef) {
		this.resourceRef = resourceRef;
	}

	public Resource(java.lang.String crossId, java.lang.Boolean primary,
			com.cross.ResourceRef resourceRef) {
		this.crossId = crossId;
		this.primary = primary;
		this.resourceRef = resourceRef;
	}

}