package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServiceGetResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String crossId;
	private java.lang.String name;
	private ServiceRef serviceType;

	private java.util.List<com.cross.ExternalId> externalIds;

	private java.util.List<com.cross.ServiceComponent> serviceComponents;

	private java.util.List<com.cross.CustomAttribute> customAttributes;

	public ServiceGetResponse() {
	}

	public java.lang.String getCrossId() {
		return this.crossId;
	}

	public void setCrossId(java.lang.String crossId) {
		this.crossId = crossId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.util.List<com.cross.ExternalId> getExternalIds() {
		return this.externalIds;
	}

	public void setExternalIds(java.util.List<com.cross.ExternalId> externalIds) {
		this.externalIds = externalIds;
	}

	public java.util.List<com.cross.ServiceComponent> getServiceComponents() {
		return this.serviceComponents;
	}

	public void setServiceComponents(
			java.util.List<com.cross.ServiceComponent> serviceComponents) {
		this.serviceComponents = serviceComponents;
	}

	public com.cross.ServiceRef getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(com.cross.ServiceRef serviceType) {
		this.serviceType = serviceType;
	}

	public java.util.List<com.cross.CustomAttribute> getCustomAttributes() {
		return this.customAttributes;
	}

	public void setCustomAttributes(
			java.util.List<com.cross.CustomAttribute> customAttributes) {
		this.customAttributes = customAttributes;
	}

	public ServiceGetResponse(java.lang.String crossId, java.lang.String name,
			com.cross.ServiceRef serviceType,
			java.util.List<com.cross.ExternalId> externalIds,
			java.util.List<com.cross.ServiceComponent> serviceComponents,
			java.util.List<com.cross.CustomAttribute> customAttributes) {
		this.crossId = crossId;
		this.name = name;
		this.serviceType = serviceType;
		this.externalIds = externalIds;
		this.serviceComponents = serviceComponents;
		this.customAttributes = customAttributes;
	}

}