package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServiceComponent implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String crossId;
	private java.util.List<com.cross.ExternalId> externalIds;
	private java.lang.String name;
	private java.lang.String componentTypeName;
	private java.lang.String resourceType;
	private ServiceRef serviceRef;
	private java.util.List<com.cross.Resource> resources;

	private java.util.List<com.cross.CustomAttribute> customAttributes;

	public ServiceComponent() {
	}

	public java.lang.String getCrossId() {
		return this.crossId;
	}

	public void setCrossId(java.lang.String crossId) {
		this.crossId = crossId;
	}

	public java.util.List<com.cross.ExternalId> getExternalIds() {
		return this.externalIds;
	}

	public void setExternalIds(java.util.List<com.cross.ExternalId> externalIds) {
		this.externalIds = externalIds;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getComponentTypeName() {
		return this.componentTypeName;
	}

	public void setComponentTypeName(java.lang.String componentTypeName) {
		this.componentTypeName = componentTypeName;
	}

	public java.lang.String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(java.lang.String resourceType) {
		this.resourceType = resourceType;
	}

	public com.cross.ServiceRef getServiceRef() {
		return this.serviceRef;
	}

	public void setServiceRef(com.cross.ServiceRef serviceRef) {
		this.serviceRef = serviceRef;
	}

	public java.util.List<com.cross.Resource> getResources() {
		return this.resources;
	}

	public void setResources(java.util.List<com.cross.Resource> resources) {
		this.resources = resources;
	}

	public java.util.List<com.cross.CustomAttribute> getCustomAttributes() {
		return this.customAttributes;
	}

	public void setCustomAttributes(
			java.util.List<com.cross.CustomAttribute> customAttributes) {
		this.customAttributes = customAttributes;
	}

	public ServiceComponent(java.lang.String crossId,
			java.util.List<com.cross.ExternalId> externalIds,
			java.lang.String name, java.lang.String componentTypeName,
			java.lang.String resourceType, com.cross.ServiceRef serviceRef,
			java.util.List<com.cross.Resource> resources,
			java.util.List<com.cross.CustomAttribute> customAttributes) {
		this.crossId = crossId;
		this.externalIds = externalIds;
		this.name = name;
		this.componentTypeName = componentTypeName;
		this.resourceType = resourceType;
		this.serviceRef = serviceRef;
		this.resources = resources;
		this.customAttributes = customAttributes;
	}

}