package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServiceListResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer totalCount;
	private java.lang.Boolean hasMore;

	private java.util.List<com.cross.ServiceItem> items;

	public ServiceListResponse() {
	}

	public java.lang.Integer getTotalCount() {
		return this.totalCount;
	}

	public void setTotalCount(java.lang.Integer totalCount) {
		this.totalCount = totalCount;
	}

	public java.lang.Boolean getHasMore() {
		return this.hasMore;
	}

	public void setHasMore(java.lang.Boolean hasMore) {
		this.hasMore = hasMore;
	}

	public java.util.List<com.cross.ServiceItem> getItems() {
		return this.items;
	}

	public void setItems(java.util.List<com.cross.ServiceItem> items) {
		this.items = items;
	}

	public ServiceListResponse(java.lang.Integer totalCount,
			java.lang.Boolean hasMore,
			java.util.List<com.cross.ServiceItem> items) {
		this.totalCount = totalCount;
		this.hasMore = hasMore;
		this.items = items;
	}

}