package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServiceComponentPost implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String componentTypeName;

	public ServiceComponentPost() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getComponentTypeName() {
		return this.componentTypeName;
	}

	public void setComponentTypeName(java.lang.String componentTypeName) {
		this.componentTypeName = componentTypeName;
	}

	public ServiceComponentPost(java.lang.String name,
			java.lang.String componentTypeName) {
		this.name = name;
		this.componentTypeName = componentTypeName;
	}

}