package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServiceItem implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String crossId;

	public ServiceItem() {
	}

	public java.lang.String getCrossId() {
		return this.crossId;
	}

	public void setCrossId(java.lang.String crossId) {
		this.crossId = crossId;
	}

	public ServiceItem(java.lang.String crossId) {
		this.crossId = crossId;
	}

}