package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServiceCreateBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String serviceType;
	private java.util.List<com.cross.ServiceComponentPost> serviceComponents;

	public ServiceCreateBody() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(java.lang.String serviceType) {
		this.serviceType = serviceType;
	}

	public java.util.List<com.cross.ServiceComponentPost> getServiceComponents() {
		return this.serviceComponents;
	}

	public void setServiceComponents(
			java.util.List<com.cross.ServiceComponentPost> serviceComponents) {
		this.serviceComponents = serviceComponents;
	}

	public ServiceCreateBody(java.lang.String name,
			java.lang.String serviceType,
			java.util.List<com.cross.ServiceComponentPost> serviceComponents) {
		this.name = name;
		this.serviceType = serviceType;
		this.serviceComponents = serviceComponents;
	}

}